### ISSUE TITLE
Checklist for matilda vignette

### ISSUE THREAD

**Issue by jk-brown** [jk-brown/matilda#40]
- [x] Edit `iterate_hector` inputs -- new output = Big 4 clim vars for all years (`1745:2300`)
   - [x] Edit example in doc
   - [x] Edit example hector output
   
- [x] Edit vignette with changes made to `iterate_hector` - New branch 

- [x] Cite SD values in `generate_params` doc

Secondary importance: 
- [x]  Code coverage badge
- [x] addressing issue with `iterate_hector` errors - [issue 36](https://github.com/jk-brown/matilda/issues/36)
